"""empty message

Revision ID: a7d4a84f20cb
Revises: d1c03030a811
Create Date: 2023-05-01 13:39:49.321403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7d4a84f20cb'
down_revision = 'd1c03030a811'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('puns_user_id_fkey', 'puns', type_='foreignkey')
    op.create_foreign_key(None, 'puns', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'puns', type_='foreignkey')
    op.create_foreign_key('puns_user_id_fkey', 'puns', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
