"""empty message

Revision ID: 370554d0ff91
Revises: a7d4a84f20cb
Create Date: 2023-05-01 14:33:40.939171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '370554d0ff91'
down_revision = 'a7d4a84f20cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('pun_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pun_id'], ['puns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pun_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ratings')
    # ### end Alembic commands ###
